#!/bin/bash

set -o errexit
set -o nounset

# Destination output directory
DIR=$3

# Set up logging
LOG=$DIR/log.txt
exec  > ${LOG}
exec 2> ${LOG}
set -o xtrace

# Destination contigs file
ASSEMBLY=$DIR/contigs.fa

# Source reads in this container
READS=$2

TMP=$(mktemp -d)

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
	echo "Abort, no proc found for ${PROC}."
	exit 1
fi

eval ${CMD}
cp ${TMP}/contigs.fasta ${ASSEMBLY}
